### ISSUE TITLE
Add error bodies for events ingestion in signoz

### ISSUE THREAD

**Issue by detj** [measure-sh/measure#1163]
## Summary

Error response bodies are not visible on SigNoz self host dashboard. This makes debugging effort difficult. Add response body for errors for `/events` and `/builds` APIs. Make sure the error response body are visible in SigNoz dashboard. Also, add the HTTP Host header value.

## Tasks

- [ ] Add HTTP response body for non 2xx responses for PUT `/events` API in SigNoz
- [ ] Add HTTP response body for non 2xx responses for PUT `/builds` API in SigNoz
- [ ] Add HTTP Host header value for all requests
