### ISSUE TITLE
API to manually start and stop the SDK 

### ISSUE THREAD

**Issue by abhaysood** [measure-sh/measure#1532]
# Summary

To support manual start and stop of the SDK, following changes will be required.

The API should provide control over event collection, which is particularly useful in following scenarios:
* Large, multi-feature apps where session replay might be needed only in specific sections or features.
* Scenarios requiring targeted tracking based on a remote configuration on user segments, device types, app versions, etc.

# Tasks

- [x] Expose APIs to start and stop the SDK.
- [x] Expose config to control non-crashed session sampling rate.
- [x] Implement ability to unregister collectors:
  - [x] `UnhandledExceptionCollector`
  - [x] `AnrCollector`
  - [x] `LifecycleCollector`
  - [x] `CpuUsageCollector`
  - [x] `MemoryUsageCollector`
  - [x] `ComponentCallbacksCollector`
  - [x] `GestureCollector`
  - [x] `NetworkChangesCollector`
  - [x] `PeriodicEventExporter`
  - [x] `UserTriggeredEventCollector`
  - [x] `OkHttpCollector`
- [x] Make register function for collectors idempotent:
  - [x] `UnhandledExceptionCollector`
  - [x] `AnrCollector`
  - [x] `LifecycleCollector`
  - [x] `CpuUsageCollector`
  - [x] `MemoryUsageCollector`
  - [x] `ComponentCallbacksCollector`
  - [x] `GestureCollector`
  - [x] `NetworkChangesCollector`
  - [x] `PeriodicEventExporter`
  - [x] `UserTriggeredEventCollector`
  - [x] `OkHttpCollector`
- [x] Decouple collectors from cold launch callback.
  - [x] Find a new place to process app exits 
- [x] Continue collecting launch metrics even if SDK is not started.
- [x] Testing
- [x] Documentation

# Related Issue
Feature request: #1528

**Comment by abhaysood** [comment]
`start` and `stop` are a bit too vague, given the SDK will always collect crashes and launch metrics. To make the API more clear I am planning to introduce an `EventTrackingLevel` — can be `Full` or `Basic`.

```kotlin
// initialize SDK with `Basic` tracking level
Measure.init(context, MeasureConfig(EventTrackingLevel.Basic)`

// change the tracking level at any time
Measure.setEventTrackingLevel(EventTrackingLevel.Full)`
```

With `Basic` level, only crashes and launch metrics are collected, features like session replay and user journey will not work.
With `Full` level, all events will be collected.

**Comment by abhaysood** [comment]
Updated API:

```kotlin
// Initialize SDK by delaying the "start"
Measure.init(
  context,
  MeasureConfig(
     startOnInit = false,
     nonErrorSessionSamplingRate = 0.5f,
  ),
)

// Start tracking
Measure.start()

// Stop tracking
Measure.stop()
```
