### ISSUE TITLE
Expose API to query crash rate over time for a particular crash with optional filters (time period, device parameters, app version)

### ISSUE THREAD

**Issue by detj** [measure-sh/measure#184]
## Task summary

- [x] Expose a stubbed API with dummy auth and randomized data for the `/dashboard/overview` page
- [ ] Hook up auth and RBAC transparently without changing the API response structure
- [ ] Implement various filters like:
  - [ ] `id` alias of `app_id`
  - [ ] `from`
  - [ ] `to`
  - [ ] `version`

## Endpoint Design

Develop 2 API endpoints with the following design

1. `/apps/:id/journey?from=<timestamp>&to=<timestamp>&version=<version>`
2. `/apps/:id/metrics?from=<timestamp>&to=<timestamp>&version=<version>`

## Filtering

All filters are optional. The API server should assume sane defaults in the absence of query parameters. If parameters are present, the server should always respond with data respecting the filters accordingly.

### `from` & `to` time filters

1. If `from` or `to` are not present, then assume default UTC timestamp values for from and to as per common business settings of all users
2. If `from` is greater than `to`, return an `InvalidDateRange` error
3. If `from` is present but `to` is not present, return an `IncompleteDateRange` error

### `version` filter

1. If `version` is not present, always fallback to the latest version of the app
2. If `version` is not found, return a `VersionNotFound` 404 error
