### ISSUE TITLE
chore(backend): optimize session upload

### ISSUE THREAD

**Issue by detj** [measure-sh/measure#393]
## Summary

Session data upload by running sessionator takes more time than than it should. This affects our development productivity.

## Tasks

- [ ] Upload mapping & attachment files to a localized S3-like instance (minio, maybe)
- [ ] Add checksum checks during attachment upload. Do not re-upload, already uploaded attachments
- [ ] Modify sessionator to upload sessions in parallel. Make the concurrent value configurable through external settings.
