### ISSUE TITLE
Design a API to allow configuring features in Measure SDK

### ISSUE THREAD

**Issue by abhaysood** [measure-sh/measure#574]
* A default config should ship with the SDK
* The config should be remotely configurable
* Clients must be able to change the default config
* Review #530 

---
# Tasks
- [x] decouple SDK initialisation from content provider.
- [x] create a public `MeasureConfig` class to allow clients to pass in a custom configuration, initialize it with defaults.
- [x] refactor: remove `MeasureApi` interface as it is unused.
- [x] expose a public API to initialise measure SDK with `MeasureConfig`.
- [x] replace `Config` object with `MeasureConfig`.
- [x] update sample app to initialise the SDK.
- [x] review SDK initialisation in `androidTests`.
- [x] update documentation to showcase how to initialize and configure the SDK.
- [x] update internal documentation.
